replicaCount: 1

image:
  repository: gcr.io/cybernetic-hue-292817/bek-salizhan-test1 
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  paths:
  - '/'
  hosts:
    - rlt.bsalizhan.com
  tls:
  - hosts:
    - rlt.bsalizhan.com
    secretName: chart-rlt-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}